GET http://localhost:8080/exchange/NMS/quotes
Accept: application/json

###

GET http://localhost:8080/exchange/NMS/GOOG
Accept: application/json

###

GET http://localhost:8080/exchange/NMS/GOOG/description
Accept: text/plain

###

GET http://localhost:8080/exchange/NMS/GOOG/history/0
Accept: application/json

###

POST http://localhost:8080/auth/rhino/register
Content-Type: Application/json

{
    "name": "test",
    "username": "test",
    "password": "test"
}

###

POST http://localhost:8080/auth/rhino
Content-Type: Application/json

{
    "username": "test",
    "password": "test"
}

###

POST http://localhost:8080/auth/rhino/refresh
Content-Type: Application/json
token: 00008012-95a3-8dbc-0000-801295a38f47

###

POST http://localhost:8080/auth/rhino/logout
Content-Type: Application/json
token: 00008179-9f0e-d284-0000-81799f0ed40f

###

POST http://localhost:8080/trade/order/submit
Content-Type: Application/json
token: 0829b12c-4400-4ef8-bb73-b1eebfb13c3e

{
    "symbol": "GOOG",
    "traderUsername": "test",
    "accountUUID": "fda92c05-5748-4244-9321-77a887f6df7f",
    "brokerageName": "rhino",
    "exchangeName": "NMS",
    "transactionType": "SELL",
    "orderType": "MARKET",
    "qty": 500,
    "limitPrice": 0.0
}